In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.metrics import accuracy_score, confusion_matrix, mean_absolute_error, mean_squared_error
import numpy as np
from sklearn.preprocessing import LabelEncoder

# Load datasets
iris_df = pd.read_csv("iris.csv")
drug_df = pd.read_csv("drug.csv")
petrol_df = pd.read_csv("petrol_consumption.csv")

# Prepare IRIS dataset
X_iris = iris_df.drop(columns=["species"])
y_iris = iris_df["species"]
X_train_iris, X_test_iris, y_train_iris, y_test_iris = train_test_split(X_iris, y_iris, test_size=0.2, random_state=42)

# Train Decision Tree Classifier for IRIS
iris_clf = DecisionTreeClassifier(random_state=42)
iris_clf.fit(X_train_iris, y_train_iris)
y_pred_iris = iris_clf.predict(X_test_iris)

# IRIS Metrics
print("Iris Accuracy:", accuracy_score(y_test_iris, y_pred_iris))
print("Iris Confusion Matrix:\n", confusion_matrix(y_test_iris, y_pred_iris))

# Prepare Drug dataset (encode categorical variables)
label_encoders = {}
for col in ["Sex", "BP", "Cholesterol"]:
    label_encoders[col] = LabelEncoder()
    drug_df[col] = label_encoders[col].fit_transform(drug_df[col])

X_drug = drug_df.drop(columns=["Drug"])
y_drug = drug_df["Drug"]
X_train_drug, X_test_drug, y_train_drug, y_test_drug = train_test_split(X_drug, y_drug, test_size=0.2, random_state=42)

# Train Decision Tree Classifier for Drug dataset
drug_clf = DecisionTreeClassifier(random_state=42)
drug_clf.fit(X_train_drug, y_train_drug)
y_pred_drug = drug_clf.predict(X_test_drug)

# Drug Metrics
print("Drug Accuracy:", accuracy_score(y_test_drug, y_pred_drug))
print("Drug Confusion Matrix:\n", confusion_matrix(y_test_drug, y_pred_drug))

# Prepare Petrol Consumption dataset
X_petrol = petrol_df.drop(columns=["Petrol_Consumption"])
y_petrol = petrol_df["Petrol_Consumption"]
X_train_petrol, X_test_petrol, y_train_petrol, y_test_petrol = train_test_split(X_petrol, y_petrol, test_size=0.2, random_state=42)

# Train Decision Tree Regressor for Petrol dataset
petrol_reg = DecisionTreeRegressor(random_state=42)
petrol_reg.fit(X_train_petrol, y_train_petrol)
y_pred_petrol = petrol_reg.predict(X_test_petrol)

# Petrol Regression Metrics
print("Mean Absolute Error (MAE):", mean_absolute_error(y_test_petrol, y_pred_petrol))
print("Mean Squared Error (MSE):", mean_squared_error(y_test_petrol, y_pred_petrol))
print("Root Mean Squared Error (RMSE):", np.sqrt(mean_squared_error(y_test_petrol, y_pred_petrol)))


Iris Accuracy: 1.0
Iris Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Drug Accuracy: 1.0
Drug Confusion Matrix:
 [[ 6  0  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  5  0  0]
 [ 0  0  0 11  0]
 [ 0  0  0  0 15]]
Mean Absolute Error (MAE): 94.3
Mean Squared Error (MSE): 17347.7
Root Mean Squared Error (RMSE): 131.7106677532234
